### ISSUE TITLE
FastHex.kt needs attribution

### ISSUE THREAD

**Issue by esaulpaugh** [Kr1ptal/ethers-kt#108]
### Module

Other

### 📝 Description

FastHex.kt is based on FastHex.java by Evan Saulpaugh i.e. me: https://github.com/esaulpaugh/headlong/blob/master/src/main/java/com/esaulpaugh/headlong/util/FastHex.java

You do not have permission to use it except in keeping with the license requirements. One of the requirements is "You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work".

Thanks.

**Comment by ArtificialPB** [comment]
I see the resemblance with the class and some variable names. It's likely that our implementation is based on yours, and that we forgot to add the attribution.

I'm AFK until Monday, but I saw that you have a patch for this ready on your fork. I'm happy to assist you with opening a PR here if you encountered any issues. Otherwise, I can add this myself when I get back.

Thanks

**Comment by esaulpaugh** [comment]
I opened a PR but I'm pretty sure someone deleted it.

**Comment by ArtificialPB** [comment]
Only issues can be deleted, there is no option to delete a PR.

Can you please try opening the PR again? In case there's anything preventing you from opening it, I'd be really grateful if you'd let me know as this would be a major issue, and would like to get it resolved asap!

**Comment by esaulpaugh** [comment]
https://github.com/Kr1ptal/ethers-kt/pull/109
